- type: job
  parent: CMSurvivor
  id: CMSurvivorLv624ColonyAdmin
  name: rmc-job-name-survivor-lv624-admin
  description: cm-job-description-survivor
  playTimeTracker: RMCJobSurvivorCO
  ranks:
    RMCRankCivilianColonyAdmin: []
  startingGear: RMCGearSurvivorLv624ColonyAdmin
  icon: RMCJobIconPMCDirector
  hasIcon: true
  accessGroups:
  - Colony
  roleWeight: 0.25
  spawnMenuRoleName: Colony Administration (LV624 Survivor)
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: RMCSkillPresetSurvivorColAdmin
    - type: EquipSurvivorPreset
      preset: RMCGearSurvivorPresetLV624ColonyAdmin
    - type: MarineOrders
    - type: RMCPointing
    - type: CommandAccent
    - type: InnateCommandSpeech
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage
    - type: NpcFactionMember
      factions:
      - Civilian
    - type: JobPrefix
      prefix: cm-job-prefix-survivor-lv624-admin
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: director
      background:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: background_pmc
  useLoadoutOfJob: RMCSurvivorCommandingOfficer # for inheritance

- type: startingGear
  parent: RMCGearSurvivorBase
  id: RMCGearSurvivorLv624ColonyAdmin
  equipment:
    id: RMCIDCardColonyAdmin
    ears: RMCHeadsetColonyIcons

- type: entity
  parent: RMCSurvivorPresetCorporate
  id: RMCGearSurvivorPresetLV624ColonyAdmin
  name: lv624 colony admin preset
  categories: [ HideSpawnMenu ]
  components:
  - type: SurvivorPreset
    primaryWeapons:
    - [ RMCWeaponSMGP90, RMCBeltSecurityWeYaFilled ]
    - [ WeaponSMGMP5, CMBeltMarineMP5 ]
    - [ RMCWeaponShotgunM42A1Filled, CMBeltMarineBuckshot ]
    primaryWeaponChance: 1
    randomOutfits:
    - [ RMCJumpsuitLiaisonExpensiveSuit ]
    - [ RMCJumpsuitLiaisonExpensiveSuitBrown ]
    - [ RMCJumpsuitLiaisonExpensiveSuitJacket ]
    - [ RMCJumpsuitLiaisonExpensiveSuitBrownJacket ]
    - [ RMCJumpsuitLiaisonExpensiveSuitJacketOnly ]
    - [ RMCJumpsuitWornSuit ]
    - [ RMCJumpsuitGreySuitPants ]
    - [ RMCJumpsuitBlueWorkwear ]
    - [ RMCMarshalCMBUniform ]
    randomGearOther:
    -
      - [ CMSheetMetal20, CMPenClicky, CMClipboard ]
    randomStartingGear:
      shoes:
      - RMCShoesLaceup
      - RMCShoesLaceupBrown
      - RMCBootsCorporate
      eyes:
      - RMCGlassesAviators
      - RMCSunglassesBig
      outerClothing:
      - RMCCoatExpensiveFur
      - RMCCoatExpensiveFurAlt
      - RMCArmorVestWeYaAlt
      - RMCArmorVestWeYaAlt
      - RMCArmorVestWeYaAlt

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointSolarisLV624ColonyAdmin
  name: LV624 colony admin spawn point
  components:
  - type: SpawnPoint
    job_id: CMSurvivorLv624ColonyAdmin
  - type: Sprite
    state: co_spawn
