- type: job
  parent: CMSurvivorCorporate
  id: CMSurvivorLV624CorporateLiaison
  name: rmc-job-name-survivor-lv624-corporate-liaison
  description: cm-job-description-survivor
  spawnMenuRoleName: Corporate Liaison (LV624 Survivor)
  startingGear: RMCGearSurvivorLV624CorporateLiaison

- type: startingGear
  parent: RMCGearSurvivorBaseNoBackpack
  id: RMCGearSurvivorLV624CorporateLiaison
  equipment:
    ears: RMCHeadsetDistressWeYa
    id: CMIDCardLiaisonColony
    pocket2: CMClipboard

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorLV624CorporateLiaison
  name: survivor lv624 coporate liaison spawn point
  components:
  - type: SpawnPoint
    job_id: CMSurvivor
  - type: Sprite # TODO: Replace with landmark sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - sprite: _RMC14/Markers/cm_jobs.rsi
      state: survivor

- type: entity
  parent: RMCSurvivorPresetCorporate
  id: RMCGearSurvivorPresetLV624CorporateLiaison
  name: lv624 colonist preset
  categories: [ HideSpawnMenu ]
  components:
  - type: SurvivorPreset
    randomOutfits:
    - [ RMCJumpsuitLiaisonExpensiveSuit ]
    - [ RMCJumpsuitLiaisonExpensiveSuitBrown ]
    - [ RMCJumpsuitLiaisonExpensiveSuitJacket ]
    - [ RMCJumpsuitLiaisonExpensiveSuitBrownJacket ]
    - [ RMCJumpsuitLiaisonExpensiveSuitJacketOnly ]
    - [ RMCJumpsuitWornSuit ]
    - [ RMCJumpsuitGreySuitPants ]
    - [ RMCJumpsuitBlueWorkwear ]
    randomGearOther:
    -
      - [ CMSheetMetal20, RMCSpaceCash1000, CMPenClicky, CMClipboard ]
      - [ CMSheetMetal20, RMCSpaceCash1000, CMPenClicky, CMClipboard ]
      - [ CMWeaponPistolM1984Custom, CMSheetMetal20, CMPenClicky, CMClipboard ]
    randomStartingGear:
      back:
      - CMSatchel
      - RMCSatchelBlack
      shoes:
      - RMCShoesLaceup
      - RMCShoesLaceupBrown
      - RMCBootsCorporate
      eyes:
      - RMCGlassesAviators
      - RMCSunglassesBig
      outerClothing:
      - RMCCoatExpensiveFur
      - RMCCoatExpensiveFurAlt
      - RMCCoatBomberGrey
      - RMCArmorVestWeYaAlt
