- type: job
  parent: CMSurvivorDoctor
  id: CMSurvivorLV624MedicalDoctor
  name: rmc-job-name-survivor-medical-doctor
  description: cm-job-description-survivor
  startingGear: RMCGearSurvivorLV624MedicalDoctor
  spawnMenuRoleName: Medical Doctor (LV624 Survivor)
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 1
        RMCSkillEndurance: 2
        RMCSkillFireman: 1
        RMCSkillFirearms: 1
        RMCSkillMedical: 3
        RMCSkillSurgery: 2
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: NpcFactionMember
      factions:
      - Civilian
    - type: IntelRescueSurvivorObjective
    - type: RMCAllowSuitStorage
    - type: EquipSurvivorPreset
      preset: RMCGearSurvivorPresetLV624MedicalDoctor
  useLoadoutOfJob: CMSurvivorDoctor # for inheritance

- type: startingGear
  parent: RMCGearSurvivorBase
  id: RMCGearSurvivorLV624MedicalDoctor
  equipment:
    shoes: RMCShoesWhite
    back: CMSatchelMedical
    gloves: CMHandsLatex

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorLV624MedicalDoctor
  name: survivor lv624 medical doctor spawn point
  components:
  - type: SpawnPoint
    job_id: CMSurvivor
  - type: Sprite # TODO: Replace with landmark sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - sprite: _RMC14/Markers/cm_jobs.rsi
      state: survivor

- type: entity
  parent: RMCSurvivorPresetDoctor
  id: RMCGearSurvivorPresetLV624MedicalDoctor
  name: lv624 medical doctor colonist preset
  categories: [ HideSpawnMenu ]
  components:
  - type: SurvivorPreset
    randomOutfits:
    - [ CMMaskSterile, CMHeadCapSurgBlue, CMScrubsBlue ]
    - [ CMMaskSterile, CMHeadCapSurgBlue, CMScrubsBlue ]
    - [ CMMaskSterile, RMCScrubsOlive, RMCLabcoatLongOpened ]
    - [ CMMaskSterile, RMCScrubsOlive, RMCLabcoatLongOpened ]
    - [ CMMaskSterile, CMJumpsuitLiaisonBlue, RMCBeltMedicalDefibAnalyzerFilled, RMCHazardVestEMTGreen ]
